spring:
  application:
    name: cephalometry
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/cephalometry"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "none"
  liquibase:
    enabled: "true"
    change-log: "classpath:changelog/changelog-master.xml"
server:
  port: 9000